INSERT INTO ACCOUNT (ID, NAME, ROLE) VALUES (1, 'Royal popuga', 0);
INSERT INTO ACCOUNT (ID, NAME, ROLE)  VALUES (2, 'PopugJS', 1);

INSERT INTO TASK (ID, DESCRIPTION, ASSIGNEE_ID, STATUS) VALUES (1, 'Awesome task 1', 1, 1);
INSERT INTO TASK (ID, DESCRIPTION, ASSIGNEE_ID, STATUS) VALUES (2, 'Awesome task 2', 2, 0);
INSERT INTO TASK (ID, DESCRIPTION, ASSIGNEE_ID, STATUS) VALUES (3, 'So-so task', 2, 1);
